### ISSUE TITLE
phpredis 4.0 - breaking api changes

### ISSUE THREAD

**Issue by smaknsk** [dcb9/yii2-phpredis#5]
phpredis 4.0 - breaking api changes 
https://pecl.php.net/package-changelog.php?package=redis

Error:
```
Exception 'ArgumentCountError' with message 'Too few arguments to function dcb9\redis\Connection::open(), 0 passed in .../vendor/dcb9/yii2-phpredis/Cache.php on line 27 and at least 1 expected'
```

**Comment by dcb9** [comment]
I think that has nothing to do with phpredis, it's one of the PHP 7.1 incompatible changes, http://php.net/manual/en/migration71.incompatible.php.

we have added default value for dcb9\redis\Connection::open(), https://github.com/dcb9/yii2-phpredis/pull/6/files#diff-eba180ff89e23df156c82c995be952dfR88, so I think it will work with PHP 7.1.

I'm looking forward to hearing your feedback
